-- Gate 1: database roles.
--
-- Run once, by the database owner, before the application connects. Passwords
-- are supplied by a named human from the deployment secret store — never
-- checked in, never generated by an automated agent. Replace the placeholders
-- below before running; the file is deliberately not executable as-is.
--
--   :migration_password   used only by the migration pipeline
--   :application_password used by the Worker
--   :support_password     used by named operations staff, read-only

-- The migration role owns the schema and may change it.
CREATE ROLE exporthq_migration LOGIN PASSWORD :'migration_password';

-- The application role is deliberately NOT the table owner and NOT BYPASSRLS.
-- A table owner bypasses row-level security by default, which would silently
-- disable every tenant policy in this repository.
CREATE ROLE exporthq_app LOGIN PASSWORD :'application_password' NOBYPASSRLS NOSUPERUSER NOCREATEDB NOCREATEROLE;

-- Read-only support access for incident investigation. Still subject to
-- row-level security, so a support session sees nothing without a context.
CREATE ROLE exporthq_support LOGIN PASSWORD :'support_password' NOBYPASSRLS NOSUPERUSER;

GRANT CONNECT ON DATABASE exporthq TO exporthq_app, exporthq_support;
GRANT USAGE ON SCHEMA public TO exporthq_app, exporthq_support;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO exporthq_app;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO exporthq_app;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO exporthq_support;

ALTER DEFAULT PRIVILEGES FOR ROLE exporthq_migration IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO exporthq_app;
ALTER DEFAULT PRIVILEGES FOR ROLE exporthq_migration IN SCHEMA public
  GRANT SELECT ON TABLES TO exporthq_support;

-- Audit is append-only for everyone that is not the migration role.
REVOKE UPDATE, DELETE ON audit_events FROM exporthq_app, exporthq_support;

-- Platform bookkeeping is not readable by support; it is operational state,
-- not evidence.
GRANT SELECT, INSERT, UPDATE, DELETE ON idempotency_keys, webhook_deliveries TO exporthq_app;

-- The identity bridge runs as its definer, so only the application may call it.
GRANT EXECUTE ON FUNCTION app_resolve_organization(text) TO exporthq_app;
GRANT EXECUTE ON FUNCTION app_upsert_organization(text, text, text, text) TO exporthq_app;
GRANT EXECUTE ON FUNCTION app_project_membership(uuid, text, text, boolean) TO exporthq_app;

-- Entitlement writes stay granted at the privilege level; row-level security
-- is what restricts them to a staff or system actor. Revoking the privilege
-- here would also block the operations path, which uses the same role.
