/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: 6b9cb8ff7cb2cc66aea14166142fdd18)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	EXPORTHQ_ENVIRONMENT: "production";
	EXPORTHQ_DEMO_MODE: "false";
	EXPORTHQ_WEB_URL: "https://export-hq.com";
	EXPORTHQ_AUTHORIZED_PARTIES: "https://export-hq.com";
	EXPORTHQ_ACTIVATION_GATES_PASSED: "";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "EXPORTHQ_ENVIRONMENT" | "EXPORTHQ_DEMO_MODE" | "EXPORTHQ_WEB_URL" | "EXPORTHQ_AUTHORIZED_PARTIES" | "EXPORTHQ_ACTIVATION_GATES_PASSED">> {}
}
